### ISSUE TITLE
The project won't start

### ISSUE THREAD

**Issue by Achudh** [SIMBAChain/CarDemo#2]
<img width="597" alt="Screenshot 2020-05-01 at 12 42 15 PM" src="https://user-images.githubusercontent.com/18098565/80789328-503b0300-8ba9-11ea-864c-b5cd3efc17b2.png">

**Comment by ihave2** [comment]
Hi,
You will need to update the apiUrl and the apiKey with yours to make it work. You can do so with following steps: 

1. Create and configure an app on Simba Dashboard with the default carDemo2 smart contract at https://app.simbachain.com/
2. Generate an apiKey for the app on App-View page
3. Open src/store/modules/info.js and replace yourApiUrl and yourApiKey with yours

**Comment by Achudh** [comment]
Thank you so much @Eric ! Will try it out ! Btw could you update the ReadMe
file with the same ? I think it would be helpful.

**Comment by Achudh** [comment]
Thank you so much @ihave2  ! Will try it out ! Btw could you update the ReadMe file with the same ? I think it would be helpful.

**Comment by ihave2** [comment]
@Achudh  No problem. The ReadMe file was updated.

**Comment by Achudh** [comment]
@ihave2 Hey! Still having trouble with the app. It is stuck in the loading. But there are no errors 
<img width="1680" alt="Screenshot 2020-05-04 at 12 36 01 PM" src="https://user-images.githubusercontent.com/18098565/80943013-d3579580-8e03-11ea-90ab-89c2a5a2f1e7.png">

**Comment by ihave2** [comment]
Hi @Achudh, its not stuck. An empty state for zero transaction was not created for this demo and the loading state(the anim you seeing) was used instead. The loading screen will be gone after one transaction has been posted. You are welcome to add an empty state to indicate there is no transaction posted if you like, but I think its ok without having it on a demo.
